version: "3"
services:
  database:
    image: "postgres:alpine"
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: tdd
    volumes:
      - ./db:/docker-entrypoint-initdb.d